# Generated by Django 3.2.7 on 2021-09-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('legajo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=15)),
                ('fecha_nac', models.DateField()),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_cliente', models.CharField(choices=[('P', 'Cliente Particular'), ('E', 'Cliente Empresa')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('legajo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=15)),
                ('fecha_nac', models.DateField()),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('nro_remito', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('valor_flete', models.FloatField()),
                ('valor_contrareembolso', models.FloatField()),
                ('medio_pago', models.CharField(choices=[('OR', 'Pago en Origen'), ('DES', 'Pago en Destino'), ('CC', 'Pago con Cuenta Corriente')], max_length=20)),
                ('legajo_chofer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.chofer')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstadoRemito',
            fields=[
                ('tipo_estado', models.CharField(choices=[('asignado', 'Estado Asignado'), ('en_circulacion', 'Estado en Circulación'), ('en_viaje', 'Estado en Viaje'), ('rendido', 'Estado Rendido'), ('segunda_entrega', 'Estado Segunda Entrega'), ('pendiente', 'Estado Pendiente'), ('pagado', 'Estado Pagado')], default='asignado', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField()),
                ('fecha_confeccion', models.DateField()),
                ('legajo_chofer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.chofer')),
                ('localidades', models.ManyToManyField(to='gestionCargas.Localidad')),
                ('remitos', models.ManyToManyField(blank=True, to='gestionCargas.Remito')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTransporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('remitente', models.CharField(max_length=20)),
                ('direccion_origen', models.CharField(max_length=20)),
                ('destinatario', models.CharField(max_length=20)),
                ('direccion_destinatario', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.cliente')),
                ('localidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='localidades_destino', to='gestionCargas.localidad')),
                ('localidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='localidades_origen', to='gestionCargas.localidad')),
            ],
        ),
        migrations.AddField(
            model_name='remito',
            name='solicitud_transporte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.solicitudtransporte'),
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField()),
                ('id_cliente', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRemito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True)),
                ('actual', models.BooleanField()),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.remito')),
                ('tipo_estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.tipoestadoremito')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cuit', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('id_cliente', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='remito',
            name='solicitud_transporte',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.solicitudtransporte'),
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField()),
                ('id_cliente', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='estadoremito',
            name='tipo_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.tipoestadoremito'),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cuit', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('id_cliente', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.localidad'),
        ),
        migrations.CreateModel(
            name='Bulto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('tipo', models.CharField(choices=[('CH', 'Bulto chico (hasta 10kg)'), ('M', 'Bulto mediano (entre 10kg y 25kg)'), ('G', 'Bulto grande (más de 25kg)')], max_length=10)),
                ('descripcion', models.CharField(max_length=20)),
                ('valor_flete', models.FloatField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.solicitudtransporte')),
            ],
        ),
    ]
