# Generated by Django 3.2.7 on 2021-09-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('legajo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=15)),
                ('tipo_doc', models.CharField(max_length=5)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=15)),
                ('tipo_doc', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('legajo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=15)),
                ('tipo_doc', models.CharField(max_length=5)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRemito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('nro_remito', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('valor_flete', models.FloatField()),
                ('valor_contrareembolso', models.FloatField()),
                ('solicitud_transporte', models.CharField(max_length=10)),
                ('estado_actual', models.ManyToManyField(to='gestionCargas.EstadoRemito')),
                ('legajo_chofer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.chofer')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_viaje', models.CharField(max_length=4)),
                ('fecha_salida', models.DateField()),
                ('fecha_confeccion', models.DateField()),
                ('patente', models.CharField(max_length=10)),
                ('legajo_chofer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.chofer')),
                ('localidades', models.ManyToManyField(to='gestionCargas.Localidad')),
                ('remitos', models.ManyToManyField(to='gestionCargas.Remito')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTransporte',
            fields=[
                ('id_solicitud', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('direccion_origen', models.CharField(max_length=20)),
                ('destinatario', models.CharField(max_length=20)),
                ('direccion_destinatario', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.cliente')),
                ('localidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.localidad')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.localidad'),
        ),
        migrations.CreateModel(
            name='Bulto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('tipo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=20)),
                ('valor_flete', models.FloatField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionCargas.solicitudtransporte')),
            ],
        ),
    ]
