# Generated by Django 3.2.7 on 2021-09-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCargas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='medio_pago',
            field=models.CharField(choices=[('OR', 'Pago en Origen'), ('DES', 'Pago en Destino'), ('CC', 'Pago con Cuenta Corriente')], default='DES', max_length=20),
            preserve_default=False,
        ),
    ]
