# Generated by Django 3.2.7 on 2021-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCargas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoremito',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
