# Generated by Django 3.2.7 on 2021-10-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCargas', '0004_auto_20211016_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtransporte',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
