# Generated by Django 3.2.7 on 2021-10-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCargas', '0005_alter_solicitudtransporte_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remito',
            name='valor_contrareembolso',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='remito',
            name='valor_flete',
            field=models.FloatField(null=True),
        ),
    ]
