# Generated by Django 3.2.7 on 2021-10-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCargas', '0006_auto_20211019_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
