# Generated by Django 3.2.7 on 2021-10-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCargas', '0007_hists'),
    ]

    operations = [
        migrations.AddField(
            model_name='hists',
            name='valor',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hists',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
