# Generated by Django 3.2.7 on 2021-11-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('legajo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=15)),
                ('fecha_nac', models.DateField()),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('nro_remito', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField()),
                ('valor_flete', models.FloatField(null=True)),
                ('valor_contrareembolso', models.FloatField(null=True)),
                ('medio_pago', models.CharField(choices=[('OR', 'Pago en Origen'), ('DES', 'Pago en Destino'), ('CC', 'Pago con Cuenta Corriente')], max_length=20, null=True)),
                ('legajo_chofer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicioRemitos.chofer')),
            ],
        ),
    ]
