# Generated by Django 3.2.7 on 2021-11-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicioRemitos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_cliente', models.CharField(choices=[('P', 'Cliente Particular'), ('E', 'Cliente Empresa')], max_length=20)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicioRemitos.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstadoRemito',
            fields=[
                ('tipo_estado', models.CharField(choices=[('asignado', 'Estado Asignado'), ('en_circulacion', 'Estado en Circulación'), ('en_viaje', 'Estado en Viaje'), ('rendido', 'Estado Rendido'), ('segunda_entrega', 'Estado Segunda Entrega'), ('pendiente', 'Estado Pendiente'), ('pagado', 'Estado Pagado')], default='asignado', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTransporte',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('remitente', models.CharField(max_length=20)),
                ('direccion_origen', models.CharField(max_length=20)),
                ('destinatario', models.CharField(max_length=20)),
                ('direccion_destinatario', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicioRemitos.cliente')),
                ('localidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='localidades_destino', to='servicioRemitos.localidad')),
                ('localidad_origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='localidades_origen', to='servicioRemitos.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField()),
                ('id_cliente', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='servicioRemitos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRemito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('actual', models.BooleanField()),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicioRemitos.remito')),
                ('tipo_estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicioRemitos.tipoestadoremito')),
            ],
        ),
        migrations.CreateModel(
            name='Bulto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('tipo', models.CharField(choices=[('CH', 'Bulto chico (hasta 10kg)'), ('M', 'Bulto mediano (entre 10kg y 25kg)'), ('G', 'Bulto grande (más de 25kg)')], max_length=10)),
                ('descripcion', models.CharField(max_length=20)),
                ('valor_flete', models.FloatField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicioRemitos.solicitudtransporte')),
            ],
        ),
        migrations.AddField(
            model_name='remito',
            name='solicitud_transporte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='servicioRemitos.solicitudtransporte'),
        ),
    ]
