# Generated by Django 3.2.7 on 2021-11-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicioRemitos', '0002_auto_20211117_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField()),
                ('fecha_confeccion', models.DateField()),
                ('legajo_chofer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicioRemitos.chofer')),
                ('localidades', models.ManyToManyField(to='servicioRemitos.Localidad')),
                ('remitos', models.ManyToManyField(blank=True, to='servicioRemitos.Remito')),
            ],
        ),
    ]
